//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Hospital
{


    public partial class WebForm2
    {

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new WebApp_Hospital.SiteMaster Master
        {
            get
            {
                return ((WebApp_Hospital.SiteMaster)(base.Master));
            }
        }
    }
}
