// <auto-generated />
namespace Caja.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Procedimientos_Paola : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Procedimientos_Paola));
        
        string IMigrationMetadata.Id
        {
            get { return "202304201505548_Procedimientos_Paola"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
