// <auto-generated />
namespace CORE_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class JsonIgnoreUsuarioHistoricoAcciones : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JsonIgnoreUsuarioHistoricoAcciones));
        
        string IMigrationMetadata.Id
        {
            get { return "202304200703408_JsonIgnoreUsuarioHistoricoAcciones"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
